#!/usr/bin/python
#encoding:utf-8

input = open('data.txt', 'r')
for line in input:
	line = line.replace('!', '')
	line = line.replace('@', '')
	line = line.replace('#', '')
	line = line.replace('$', '')
	line = line.replace('%', '')
	line = line.replace('^', '')
	line = line.replace('&', '')
	line = line.replace('*', '')
	line = line.replace('(', '')
	line = line.replace(')', '')
	line = line.replace('_', '')
	line = line.replace('-', '')
	line = line.replace('+', '')
	line = line.replace('=', '')
	line = line.replace('[', '')
	line = line.replace(']', '')
	line = line.replace('{', '')
	line = line.replace('}', '')
	line = line.replace('|', '')
	line = line.replace('"', '')
	line = line.replace("'", '')
	line = line.replace(':', '')
	line = line.replace(';', '')
	line = line.replace('?', '')
	line = line.replace('.', '')
	line = line.replace(',', '')
	line = line.replace('！', '')
	line = line.replace('“', '')
	line = line.replace('”', '')
	line = line.replace('，', '')
	line = line.replace('。', '')
	line = line.replace('：', '')
	line = line.replace('；', '')
	line = line.replace('‘', '')
	line = line.replace('’', '')
	line = line.replace('《', '')
	line = line.replace('》', '')
	line = line.replace('\n', '')
	line = line.replace('？', '')
	line = line.replace('/', '')
	print line

